global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'vibe_backend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['backend_nginx:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']
